paths:
  /api/products/:
    get:
      summary: Obtener todos los productos con paginación, filtro y ordenamiento para la store. NO retornar productos con status false (inactivos).
      tags:
        - Products
      responses:
        "200":
          description: "Los productos fueron obtenido existosamente."
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#components/schemas/Product"

        "400":
          description: "Error en la obtencion de los productos."
    post:
      summary: "Crear un nuevo producto. Solo usuarios con rol Premium o Admin pueden crear productos."
      tags:
        - Products
      responses:
        "201":
          description: "El producto se creo y se almacenó en la base de datos exitosamente"
  /api/products/admin: 
    get:
      summary: "Obtener todos los productos para el panel de administración. Retornar todos los productos, incluyendo los inactivos (status false). Solo usuarios con rol Admin pueden acceder a esta ruta."
      tags:
        - Products
      responses:
        "200":
          description: "Productos obtenidos exitosamente"
  /api/products/{id}:
    put:
      summary: "Actualizar un producto por su ID. Solo el Admin pueden actualizar productos"
      tags:
        - Products
      parameters:
      - name: id
        in: path
        required: true
        description: "ID del producto"
        schema: 
          $type: String
      responses:
        "200":
          description: "El producto fue actualizado existosamente."
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#components/schemas/Product"

        "404":
          description: "Producto no encontrado"
    delete:
      summary: "Eliminar un producto de Vendedor. Solo usuarios con rol Premium o Admin pueden eliminar productos. Premium solo puede eliminar sus productos, Admin puede eliminar cualquier producto."
      tags:
        - Products
      parameters:
      - name: id
        in: path
        required: true
        description: "ID del producto"
        schema: 
          $type: String
      responses:
        "200":
          description: "Producto borrado exitosamente"
        "404":
          description: 'El producto no existe o no tienes permiso'
  /api/products/:product_id/:seller_id:
    get:
      summary: "Obtener un producto por ID de seller_product. La relacion entre productos y users es a través de seller_products."
      tags:
        - Products
      parameters:
      - name: product_id
        in: path
        required: true
        description: "ID del producto"
        schema: 
          $type: String
      - name: seller_id
        in: path
        required: true
        description: "ID del vendedor (usuario premium)"
        schema: 
          $type: String
      responses:
        "200":
          description: "Producto obtenido exitosamente"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#components/schemas/Product"
        "404":
          description: "Producto no encontrado"
  /api/products/:product_id/seller/:seller_id:
    put:
      summary: "Actualizar el status, stock y precio del producto."
      tags:
        - Products
      parameters:
      - name: product_id
        in: path
        required: true
        description: "ID del producto"
        schema: 
          $type: String
      - name: seller_id
        in: path
        required: true
        description: "ID del vendedor (usuario premium)"
        schema: 
          $type: String
      responses:
        "200":
          description: "Producto actualizado exitosamente"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#components/schemas/Product"
        "404":
          description: "Producto no encontrado"
  /api/products/comment:
    post:
      summary: "Agregar un comentario a un producto. Solo usuarios autenticados pueden comentar."
      tags:
        - Products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                product_id:
                  type: number
                  description: "ID del producto al que se le agregará el comentario"
                comment:
                  type: string
                  description: "El comentario que se desea agregar al producto"
              example:
                product_id: 1
                comment: "Este producto es excelente, lo recomiendo mucho!"
      responses:
        "201":
          description: "Comentario agregado exitosamente"
        "400":
          description: "Error al agregar el comentario. Verificar que el producto exista y que el usuario esté autenticado."
components:
  schemas:
    Category:
      type: object
      properties:
        id: 
          type: number
          description: "ID Categoria generado por la base de datos"
        name: 
          type: String
          description: "Nombre de la Categoria"
        slug: 
          type: String
          description: "Slug de la Categoria"
        parent_id: 
          type: number
          description: "ID de la Categoria padre. Si es null, es una categoria raíz."
        path: 
          type: String
          description: "Ruta completa de la categoria, incluyendo sus padres. Ejemplo: 'Tecnología/Celulares/Smartphones'"
        is_active: 
          type: Boolean
          description: "Indica si la categoria está activa o inactiva. Solo las categorias activas se muestran en la tienda."
        created_at: 
          type: Timestamp
          description: "Fecha de creación de la categoria"
        updated_at: 
          type: Timestamp
          description: "Fecha de actualización de la categoria"
      example:
        id: 1
        name: Tecnología
        slug: tecnologia
        parent_id: null
        path: tecnologia
        is_active: true
        created_at: 2024-06-01T12:00:00Z
        updated_at: 2024-06-01T12:00:00Z
    Product:
      type: object
      description: "Un producto representa un artículo que se vende en la tienda. Este producto es el que se comparte entre los diferentes vendedores (usuarios premium) que lo ofrecen a la venta. La relación entre productos y vendedores se maneja a través de la tabla seller_products, donde cada vendedor puede tener un precio y stock diferente para el mismo producto."
      properties:
        id: 
          type: number
          description: "ID Producto generado por la base de datos"
        title: 
          type: String
          description: "Nombre del Producto"
        description: 
          type: String
          description: "Descripcion del Producto"
        thumbnail: 
          type: String
          description: "Ruta de imagen del Producto"
        code: 
          type: String
          description: "Identificador del propio Producto"
        status: 
          type: Boolean
          description: "Estado del Producto, true para activo y false para inactivo"
        category: 
          type: String
          description: "Las categorias son: Tecnología, Ropa, Bazar,Accesorios,Calzado"
        created_at: 
          type: Timestamp
          description: "Fecha de creación del producto"
        updated_at: 
          type: Timestamp
          description: "Fecha de actualización del producto"
      example:
        id: 1
        title: Guante Rojo
        description: Este es un producto prueba
        thumbnail: https://ruta_imagen/producto
        code: l24fdw
        status: true
        category_id: 1
        created_at: 2024-06-01T12:00:00Z
        updated_at: 2024-06-01T12:00:00Z
    Comments:
      type: object
      description: "Un comentario representa la opinión o reseña que un usuario autenticado deja sobre un producto específico. Los comentarios son compartidos entre todos los vendedores que ofrecen ese producto, ya que están asociados al producto en sí y no a un vendedor específico."
      properties:
        id: 
          type: number
          description: "ID del comentario generado por la base de datos"
        product_id: 
          type: number
          description: "ID del producto al que se le hizo el comentario"
        user_id: 
          type: number
          description: "ID del usuario que hizo el comentario"
        comment: 
          type: String
          description: "Texto del comentario realizado por el usuario sobre el producto"
        rating:
          type: number
          description: "Calificación numérica del producto dada por el usuario, por ejemplo, de 1 a 5 estrellas"
        created_at: 
          type: Timestamp
          description: "Fecha de creación del comentario"
      example:
        id: 1
        product_id: 1
        user_id: 2
        comment: "Este producto es excelente, lo recomiendo mucho!"
        rating: 5
        created_at: 2024-06-01T12:00:00Z
    Seller_Product:
      type: object
      description: "Un seller_product representa la relación entre un producto y un vendedor (usuario premium). Esta tabla permite que un mismo producto pueda ser ofrecido por diferentes vendedores con precios y stock distintos. Cada registro en esta tabla indica que un vendedor específico ofrece un producto específico a la venta, junto con el precio y el stock disponible para ese producto."
      properties:
        id: 
          type: number
          description: "ID de la relación entre producto y vendedor generado por la base de datos"
        product_id: 
          type: number
          description: "ID del Producto"
        seller_id: 
          type: number
          description: "ID del Vendedor (Usuario Premium)"
        price: 
          type: number
          description: "Precio del producto para ese vendedor"
        stock: 
          type: number
          description: "Stock disponible del producto para ese vendedor"
        status: 
          type: Boolean
          description: "Estado del producto para ese vendedor, true para activo y false para inactivo"
        created_at: 
          type: Timestamp
          description: "Fecha de creación de la relación entre producto y vendedor"
        updated_at: 
          type: Timestamp
          description: "Fecha de actualización de la relación entre producto y vendedor"
      example:
        product_id: 1
        seller_id: 2
        price: 1000
        stock: 10
        status: true
        created_at: 2024-06-01T12:00:00Z
        updated_at: 2024-06-01T12:00:00Z
