const EErrors = {
    // ENUMs
    ROUTING_ERROR: 1,
    INVALID_TYPES_ERROR: 2,
    DATABASE_ERROR: 3,
    CREATE_PRODUCT_ERROR: 4,
    CREATE_USER_ERROR: 5,
    USER_NOT_FOUND: 6,
    DATA_DB_DUPLICATED: 7
};

module.exports= EErrors